#ifndef _TASKCONFIG_
#define _TASKCONFIG_

#include "TaskConfig.h"

#define SLEEP_PERIOD 500
#define STARTUP_PERIOD 500
#define CHECKIN_PERIOD 500
#define OPEN_PERIOD 2000
#define READY_PERIOD 500
#define WASH_PERIOD 500
#define EMERGENCY_PERIOD 500
#define CHECKOUT_PERIOD 500

#endif